use_frameworks!

platform :ios, '8.0'

target 'wgPersonPrefrenceCatogeryKit_Example' do
  pod 'wgPersonPrefrenceCatogeryKit', :path => '../'

  target 'wgPersonPrefrenceCatogeryKit_Tests' do
    inherit! :search_paths

    
  end
end
